import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import localFont from "next/font/local";
import { Quattrocento } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

// Configure the font
const quattrocento = Quattrocento({
    weight: ['400', '700'], // Choose the weights you need
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${quattrocento.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
